import type { Rubric } from "../data/rubrics";
import type { ScoreLevel, ReadinessLevelInfo } from "../types";
import type { Language } from "../i18n";
import {
  calculateRubricScore,
  calculateTotalScore,
  getRubricMaxScore,
  getTotalMaxScore,
} from "./scoring";
import { parseArxivReference, getToolUrl } from "./links";

interface ExportData {
  rubrics: Rubric[];
  scores: Record<string, ScoreLevel>;
  level: ReadinessLevelInfo;
  language: Language;
}

function getDateString(): string {
  const now = new Date();
  return now.toISOString().split("T")[0];
}

function getTimestamp(): string {
  const now = new Date();
  return now.toISOString().replace(/[:.]/g, "-").slice(0, 19);
}

// Markdown Export
export function exportToMarkdown({
  rubrics,
  scores,
  level,
  language,
}: ExportData): void {
  const totalScore = calculateTotalScore(scores);
  const totalMaxScore = getTotalMaxScore(rubrics);
  const date = getDateString();

  const lines: string[] = [
    "# AI Agent Production Readiness Check Report",
    "",
    `**Date:** ${date}`,
    `**Total Score:** ${totalScore}/${totalMaxScore}`,
    `**Readiness Level:** L${level.level} - ${level.name}`,
    "",
    "---",
    "",
    "## Summary",
    "",
    `> ${level.action}`,
    "",
    "### Score by Rubric",
    "",
    "| Rubric | Score | Max |",
    "|--------|-------|-----|",
  ];

  rubrics.forEach((rubric) => {
    const rubricScore = calculateRubricScore(rubric, scores);
    const maxScore = getRubricMaxScore(rubric);
    lines.push(`| ${rubric.name[language]} | ${rubricScore} | ${maxScore} |`);
  });

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Detailed Evaluation");
  lines.push("");

  rubrics.forEach((rubric) => {
    const rubricScore = calculateRubricScore(rubric, scores);
    const maxScore = getRubricMaxScore(rubric);

    lines.push(`### ${rubric.name[language]}`);
    lines.push("");
    lines.push(`**Score:** ${rubricScore}/${maxScore}`);
    lines.push("");
    lines.push(`> ${rubric.description[language]}`);
    lines.push("");
    lines.push("| Item | Score | Level |");
    lines.push("|------|-------|-------|");

    rubric.items.forEach((item) => {
      const score = scores[item.id];
      const levelInfo = score
        ? item.levels.find((l) => l.score === score)
        : null;
      const levelLabel = levelInfo ? levelInfo.label[language] : "-";
      lines.push(
        `| ${item.id}. ${item.name[language]} | ${score ?? "-"}/5 | ${levelLabel} |`,
      );
    });

    lines.push("");

    // Add detailed item information
    rubric.items.forEach((item) => {
      const score = scores[item.id];
      const levelInfo = score
        ? item.levels.find((l) => l.score === score)
        : null;

      lines.push(`#### ${item.id}. ${item.name[language]}`);
      lines.push("");
      lines.push(
        `**${language === "ja" ? "説明" : "Description"}:** ${item.description[language]}`,
      );
      lines.push("");
      lines.push(
        `**${language === "ja" ? "評価の目的" : "Evaluation Purpose"}:** ${item.purpose[language]}`,
      );
      lines.push("");
      lines.push(
        `**${language === "ja" ? "実運用の重要性" : "Production Importance"}:** ${item.importance[language]}`,
      );
      lines.push("");
      lines.push(`**${language === "ja" ? "チェック方法" : "How to Check"}:**`);
      item.howToCheck[language].forEach((step, idx) => {
        lines.push(`${idx + 1}. ${step}`);
      });
      lines.push("");
      const toolsWithLinks = item.tools.map((tool) => {
        const url = getToolUrl(tool);
        return url ? `[${tool}](${url})` : tool;
      });
      lines.push(
        `**${language === "ja" ? "推奨ツール" : "Recommended Tools"}:** ${toolsWithLinks.join(", ")}`,
      );
      lines.push("");

      if (score && levelInfo) {
        lines.push(
          `**${language === "ja" ? "評価結果" : "Evaluation Result"}:** ${score}/5 - ${levelInfo.label[language]}`,
        );
        lines.push(`> ${levelInfo.description[language]}`);
      } else {
        lines.push(
          `**${language === "ja" ? "評価結果" : "Evaluation Result"}:** ${language === "ja" ? "未評価" : "Not evaluated"}`,
        );
      }
      lines.push("");
    });
  });

  lines.push("---");
  lines.push("");
  lines.push("## References");
  lines.push("");
  const allReferences = new Set<string>();
  rubrics.forEach((rubric) => {
    rubric.references.forEach((ref) => allReferences.add(ref));
  });
  allReferences.forEach((ref) => {
    const { text, url } = parseArxivReference(ref);
    if (url) {
      lines.push(`- [${text}](${url})`);
    } else {
      lines.push(`- ${text}`);
    }
  });
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    "*Generated by AI Agent Production Readiness Check (2025-2026 Ultimate Edition)*",
  );

  const content = lines.join("\n");
  downloadFile(
    content,
    `ai-agent-readiness-report-${getTimestamp()}.md`,
    "text/markdown",
  );
}

function downloadFile(
  content: string,
  filename: string,
  mimeType: string,
): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
